[versions]
compose = "1.11.0-alpha01"
icons-extended = "1.7.3"

[libraries]
runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
# Utils & Resources
components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose" }

materialIconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "icons-extended" }